title: Making an app to app voice call
description: You make a phone call from a web app to another web app.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a voice call from a web app to another web app using the Client SDK for JavaScript.
  content: |
    # Introduction
    In this tutorial, you will learn how to create a Client SDK application and then write the code to make a voice call from your web app to another web app.

    Two parts are needed to achieve this:

    * A web application that will make the app to app voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-app-js](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-app-js) folder.


prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli

tasks:
  - client-sdk/app-to-app/create-webhook-server
  - client-sdk/app-to-app/create-application
  - client-sdk/create-users-alice-and-bob
  - client-sdk/generate-jwts-alice-and-bob
  - client-sdk/app-to-app/place-call
  - client-sdk/app-to-app/receive-call
  - client-sdk/app-to-app/run-app

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-app-js](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-app-js) folder.

    You can do a lot more with the Client SDK. For an summary, please see the [Client SDK Overview](/client-sdk/overview) or review the [JS Client SDK documentation](/sdk/stitch/javascript/index).

    We want to hear what ideas you have in mind! Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)

    See [Client SDK documentation](/client-sdk/overview).
